
#
# Copyright (c) 2026 Broadcom. All rights reserved.
#

group = com.vmware.gemfire
version=2.0.0-build.9999

description = 'Spring Data for VMware GemFire'

minimumGradleVersion = 9.4

baseGemFireVersion=10.2
baseSpringVersion=4.1

org.gradle.parallel=true
org.gradle.workers.max=3

springTestGemfireDockerImage=gemfire/gemfire:10.2-jdk17

org.gradle.jvmargs=-Xmx3g -Dfile.encoding=UTF-8
