
#
# Copyright 2024-2025 Broadcom. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#

group = com.vmware.gemfire
version=1.0.0-build.9999

description = 'Spring Data for VMware GemFire'

minimumGradleVersion = 8.11
gemfireVersion= 10.2.+
spring-framework.version=6.2.+
spring-data-bom.version=2025.0.+
spring.gemfire.enable.private.repositories=true

org.gradle.parallel=true
org.gradle.workers.max=3

springTestGemfireDockerImage=tds-gemfire-docker-dev-local.usw1.packages.broadcom.com/pivotal-gemfire/vmware-gemfire:blessed-10.2-jdk17

org.gradle.jvmargs=-Xmx3g -Dfile.encoding=UTF-8
