[versions]
annotationApiVersion = "2.1.1"
antlrVersion = "2.7.7"
aspectJVersion = "1.9.20.1"
assertJVersion = "3.24.2"
awaitilityVersion = "4.2.2"
cacheApiVersion = "1.1.1"
cdiApiVersion = "4.0.1"
derbyVersion = "10.9.1.0"
gemFireTestContainersVersion = "2.3.1"
googleCloudStorageVersion = "2.30.2"
interceptorApiVersion = "1.2.2"
jUnitJupiterVersion = "5.10.5"
jUnitVersion = "4.13.2"
jacksonVersion = "2.16.2"
log4JVersion = "2.19.0"
logbackVersion = "1.4.14"
lombokPluginVersion = "8.6"
lombokVersion = "1.18.36"
mockitoVersion = "5.11.0"
multithreadedTCVersion = "1.01"
openWebBeansVersion = "2.0.27"
snappyVersion = "0.4"
springBootVersion = "3.2.+"
springDependencyManagementVersion = "1.1.+"
springShellVersion = "1.2.0.RELEASE"
springShiroVersion = "1.13.+"
versionCatalogUpdateVersion = "0.8.5"
versionsVersion = "0.50.0"

[libraries]
annotation-api = { module = "jakarta.annotation:jakarta.annotation-api", version.ref = "annotationApiVersion" }
antlr = { module = "antlr:antlr", version.ref = "antlrVersion" }
aspectJ = { module = "org.aspectj:aspectjweaver", version.ref = "aspectJVersion" }
assertJ = { module = "org.assertj:assertj-core", version.ref = "assertJVersion" }
awaitility = { module = "org.awaitility:awaitility", version.ref = "awaitilityVersion" }
cache-api = { module = "javax.cache:cache-api", version.ref = "cacheApiVersion" }
cdi-api = { module = "jakarta.enterprise:jakarta.enterprise.cdi-api", version.ref = "cdiApiVersion" }
derby = { module = "org.apache.derby:derbyLocale_zh_TW", version.ref = "derbyVersion" }
gemfire-core = { module = "com.vmware.gemfire:gemfire-core", version.ref = "gemfireVersion" }
gemfire-cq = { module = "com.vmware.gemfire:gemfire-cq", version.ref = "gemfireVersion" }
gemfire-deployment-chained-classloader = { module = "com.vmware.gemfire:gemfire-deployment-chained-classloader", version.ref = "gemfireVersion" }
gemfire-gfsh = { module = "com.vmware.gemfire:gemfire-gfsh", version.ref = "gemfireVersion" }
gemfire-logging = { module = "com.vmware.gemfire:gemfire-logging", version.ref = "gemfireVersion" }
gemfire-tcp-server = { module = "com.vmware.gemfire:gemfire-tcp-server", version.ref = "gemfireVersion" }
gemfire-testcontainers = { module = "dev.gemfire:gemfire-testcontainers", version.ref = "gemFireTestContainersVersion" }
gemfire-wan = { module = "com.vmware.gemfire:gemfire-wan", version.ref = "gemfireVersion" }
google-cloud-storage = { module = "com.google.cloud:google-cloud-storage", version.ref = "googleCloudStorageVersion" }
interceptor-api = { module = "javax.interceptor:javax.interceptor-api", version.ref = "interceptorApiVersion" }
jackson-annotation = { module = "com.fasterxml.jackson.core:jackson-annotations", version.ref = "jacksonVersion" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jacksonVersion" }
junit = { module = "junit:junit", version.ref = "jUnitVersion" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "jUnitJupiterVersion" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "jUnitJupiterVersion" }
junit-vintage-engine = { module = "org.junit.vintage:junit-vintage-engine", version.ref = "jUnitJupiterVersion" }
log4J = { module = "org.apache.logging.log4j:log4j-to-slf4j", version.ref = "log4JVersion" }
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logbackVersion" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombokVersion" }
mockito = { module = "org.mockito:mockito-core", version.ref = "mockitoVersion" }
multithreadedtc = { module = "edu.umd.cs.mtc:multithreadedtc", version.ref = "multithreadedTCVersion" }
openwebbeans-impl = { module = "org.apache.openwebbeans:openwebbeans-impl", version.ref = "openWebBeansVersion" }
openwebbeans-se = { module = "org.apache.openwebbeans:openwebbeans-se", version.ref = "openWebBeansVersion" }
openwebbeans-spi = { module = "org.apache.openwebbeans:openwebbeans-spi", version.ref = "openWebBeansVersion" }
snappy = { module = "org.iq80.snappy:snappy", version.ref = "snappyVersion" }
spring-boot = { module = "org.springframework.boot:spring-boot", version.ref = "springBootVersion" }
spring-shell = { module = "org.springframework.shell:spring-shell", version.ref = "springShellVersion" }
spring-shiro = { module = "org.apache.shiro:shiro-spring", version.ref = "springShiroVersion" }

[plugins]
versions = { id = "com.github.ben-manes.versions", version.ref = "versionsVersion" }
version-catalog-update = { id = "nl.littlerobots.version-catalog-update", version.ref = "versionCatalogUpdateVersion" }
lombok = { id = "io.freefair.lombok", version.ref = "lombokPluginVersion" }
dependency-management = { id = "io.spring.dependency-management", version.ref = "springDependencyManagementVersion" }

[bundles]
gemfire = ["gemfire-core", "gemfire-logging", "gemfire-cq", "gemfire-gfsh", "gemfire-wan", "gemfire-tcp-server", "gemfire-deployment-chained-classloader"]
jackson = ["jackson-annotation", "jackson-databind"]
