#
# Copyright $originalComment.match(" (\d+)", 1, "-", $today.year)2026 Broadcom. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#

#
# Copyright $originalComment.match(" (\d+)", 1, "-", $today.year)2026 Broadcom. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#

# Test Caching Application Properties
spring.application.name=TestCachingApp

# Logging
logging.level.com.example.testcaching=INFO
logging.level.org.springframework.data.gemfire=INFO
logging.level.org.apache.geode=WARN
logging.level.root=INFO
